<?php
/**
 * Created by PhpStorm.
 * User: shema
 * Date: 2018/11/24
 * Time: 16:52
 */

namespace frontend\components;

use yii\base\Widget;
use yii\helpers\Html;

class SmallBody extends Widget{
    public $body;
    public $count=3;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $mini = explode(" ",$this->body);
        if(count($mini)<=$this->count){
            $this->body;
        }else{
            array_splice($mini,$this->count);
            $this->body = implode(" ",$mini). '...';
        }

    }

    public function run()
    {
        return Html::decode($this->body,$this->count);
    }


}

